spring:
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: "org.mariadb.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
      dialect: "org.hibernate.dialect.MariaDB103Dialect"